### ISSUE TITLE
[google-oauth-ui-2] Request is missing required authentication credential

### ISSUE THREAD

**Issue by pedrow-coelho** [Bryllyant/verdaccio-google-oauth-ui#3]
## Bug Report
I'm trying to use the plugin in my values.yaml file, but it works normally in the UI interface
however, when I publish any package on verddacio it returns the following log about the plugin:

`[google-oauth-ui-2] Error: Failed requesting Google user info: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

### Versions

|             | Version |
| ----------- | ------- |
| Verdaccio   |     5.26.2 - image base /  4.12.0 - realese helm chart   |
| This plugin |     1.0.33    |

### Environment

|                  | Name | Version |
| ---------------- | ---- | ------- |
| Browser          |    google chorme  |    latest     |
| Operating system |    ubuntu  |    latest     |

### Expected behavior

publish the package without generating this log

##  **my code in values.yaml**

```
  auth:
    {{ if .Values.googleAuth.enabled -}}
    google-oauth-ui-2:
       client-id: {{ .Values.clientID }}
       client-secret: {{ .Values.clientSecret }}
       domain: {{ .Values.googleAuth.allowedDomain }}
    {{ end -}}

    htpasswd:
      file: /verdaccio/storage/htpasswd
      algorithm: bcrypt
      rounds: 10
      max_users: -2

  security:
    api:
      legacy: false
      jwt:
        sign:
          expiresIn: 30d

    web:
      sign:
        expiresIn: 1h

```

```
  packages:
    "@*/*":
      access: '$authenticated'
      publish: '$authenticated'
      unpublish: '$authenticated'
      proxy: npmjs
```
```
  middlewares:
    {{ if .Values.googleAuth.enabled -}}
    google-oauth-ui-2:
      enabled: true
    {{ end -}}

```
